import time

AVERAGE_KMH: int
TRANSFER_MINUTES: int
NUMBER_OF_EXTRA_TRANSFERS: int
TIME_WINDOW: int
KM_PER_UNIT: int
COST_PER_KM: int
CO2_PER_KM: int
CAPACITY_PER_LINE: int
MAX_DELAY_EQUATION: str
CPLEX_PATH: str
COMPUTATION_START_TIME: time
